version: 2
project_name: nanoharness

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/nanoharness
    binary: nanoharness
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X main.versionFlag={{ .Version }} -X main.commitFlag={{ .ShortCommit }} -X github.com/shubhxho/nanoharness/internal/version.Version={{ .Version }} -X github.com/shubhxho/nanoharness/internal/version.Commit={{ .ShortCommit }}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [README.md, LICENSE]

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

release:
  github:
    owner: shubhxho
    name: nanoharness
  name_template: 'v{{ .Version }}'
